### ISSUE TITLE
please provide setup/install docs

### ISSUE THREAD

**Issue by cforce** [nesty92/terraform-aws-gitlab-runner-autoscaler#7]
e.g. example variables, defining instance size - e,g. big instances with 64 porocessors , 128 GB RAM for android os builds

**Comment by nesty92** [comment]
Please check https://github.com/nesty92/terraform-aws-gitlab-runner-autoscaler/blob/1.2.0/examples/complete/main.tf.

You could control the instance type with the configuration variables in

https://github.com/nesty92/terraform-aws-gitlab-runner-autoscaler?tab=readme-ov-file#input_runner_instance_amd64

and 

https://github.com/nesty92/terraform-aws-gitlab-runner-autoscaler?tab=readme-ov-file#input_runner_instance_arm64
